version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  web_app:
    build:
      dockerfile: src/Entrypoints/FrontEnd/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"

  email_service:
    build:
      dockerfile: src/Entrypoints/EmailService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8081"

  back_office:
    build:
      dockerfile: src/Entrypoints/BackOffice/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8082"

  admin_app:
    build:
      dockerfile: src/Entrypoints/AdminApp/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8083"

volumes:
  dpkeys: