FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app

COPY ["src/Infrastructure/Infrastructure.csproj", "app/Infrastructure/"]
COPY ["src/Entrypoints/EmailService/EmailService.csproj", "app/Entrypoints/EmailService/"]

RUN dotnet restore "app/Entrypoints/EmailService/EmailService.csproj"

COPY . .

RUN dotnet publish "app/Entrypoints/EmailService/EmailService.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "EmailService.dll"]