FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app/Infrastructure

COPY ["src/Infrastructure/Infrastructure.csproj" "./"]

RUN dotnet restore 

COPY [src/Infrastructure/ ./]

WORKDIR /app/Entrypoints/AdminApp

COPY *.csproj ./

RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app/Entrypoints/AdminApp

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "AdminApp.dll"]