FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app

COPY ["src/Infrastructure/Infrastructure.csproj", "app/Infrastructure/"]
COPY ["src/Entrypoints/AdminApp/AdminApp.csproj", "app/Entrypoints/AdminApp/"]

RUN dotnet restore  "app/Entrypoints/AdminApp/AdminApp.csproj"

COPY . .

RUN dotnet publish "app/Entrypoints/AdminApp/AdminApp.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "AdminApp.dll"]