FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY ["src/Infrastructure/Infrastructure.csproj", "app/Infrastructure/"]
COPY ["src/Entrypoints/BackOffice/BackOffice.csproj", "app/Entrypoints/BackOffice/"]

RUN dotnet restore "app/Entrypoints/BackOffice/BackOffice.csproj"

COPY . .

RUN dotnet publish "app/Entrypoints/BackOffice/BackOffice.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "BackOffice.dll"]