FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app/Infrastructure

COPY ../..Infrastructure/ *.csproj ./


RUN dotnet restore 

COPY ../../Infrastructure/ ./

WORKDIR /app/ENTRYPOINTS/BackOffice

COPY *.csproj ./

RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app/ENTRYPOINTS/BackOffice

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "BackOffice.dll"]